import { StaticImageData } from "next/image";
import CSSIcon from "./css3.svg";
import FirestoreIcon from "./google-firestore.svg";
import GitIcon from "./git.svg";
import HTMLIcon from "./html5.svg";
import JavaIcon from "./java.svg";
import JavaScriptIcon from "./javascript.svg";
import JestIcon from "./jest.svg";
import MongoIcon from "./mongodb.svg";
import MySQLIcon from "./mysql.svg";
import NestIcon from "./nestjs.svg";
import NextIcon from "./nextjs.svg";
import ReactIcon from "./react.svg";
import ReactRouterIcon from "./react-router-white.svg";
import SassIcon from "./sass2.svg";
import SpringIcon from "./spring.svg";
import TailwindIcon from "./tailwindcss.svg";
import TypeScriptIcon from "./typescript.svg";

export const CSS: StaticImageData = CSSIcon;
export const Firestore: StaticImageData = FirestoreIcon;
export const Git: StaticImageData = GitIcon;
export const HTML: StaticImageData = HTMLIcon;
export const Java: StaticImageData = JavaIcon;
export const JavaScript: StaticImageData = JavaScriptIcon;
export const Jest: StaticImageData = JestIcon;
export const Mongo: StaticImageData = MongoIcon;
export const MySQL: StaticImageData = MySQLIcon;
export const Nest: StaticImageData = NestIcon;
export const Next: StaticImageData = NextIcon;
export const React: StaticImageData = ReactIcon;
export const ReactRouter: StaticImageData = ReactRouterIcon;
export const Sass: StaticImageData = SassIcon;
export const Spring: StaticImageData = SpringIcon;
export const Tailwind: StaticImageData = TailwindIcon;
export const TypeScript: StaticImageData = TypeScriptIcon;
